# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrgenter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qrgenter(object):
    def setupUi(self, qrgenter):
        qrgenter.setObjectName("qrgenter")
        qrgenter.resize(442, 198)
        self.centralwidget = QtWidgets.QWidget(qrgenter)
        self.centralwidget.setObjectName("centralwidget")
        self.gen_Button = QtWidgets.QPushButton(self.centralwidget)
        self.gen_Button.setGeometry(QtCore.QRect(230, 80, 141, 51))
        self.gen_Button.setObjectName("gen_Button")
        self.choseoutputfolder_Button = QtWidgets.QPushButton(self.centralwidget)
        self.choseoutputfolder_Button.setGeometry(QtCore.QRect(20, 80, 141, 51))
        self.choseoutputfolder_Button.setObjectName("choseoutputfolder_Button")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 351, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        qrgenter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(qrgenter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 22))
        self.menubar.setObjectName("menubar")
        qrgenter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(qrgenter)
        self.statusbar.setObjectName("statusbar")
        qrgenter.setStatusBar(self.statusbar)

        self.retranslateUi(qrgenter)
        QtCore.QMetaObject.connectSlotsByName(qrgenter)

    def retranslateUi(self, qrgenter):
        _translate = QtCore.QCoreApplication.translate
        qrgenter.setWindowTitle(_translate("qrgenter", "二维码生成器"))
        self.gen_Button.setText(_translate("qrgenter", "开始生成"))
        self.choseoutputfolder_Button.setText(_translate("qrgenter", "选择输出文件夹"))
