# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filedecoder(object):
    def setupUi(self, filedecoder):
        filedecoder.setObjectName("filedecoder")
        filedecoder.resize(747, 357)
        self.centralwidget = QtWidgets.QWidget(filedecoder)
        self.centralwidget.setObjectName("centralwidget")
        self.decode_Button = QtWidgets.QPushButton(self.centralwidget)
        self.decode_Button.setGeometry(QtCore.QRect(380, 170, 201, 71))
        self.decode_Button.setObjectName("decode_Button")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 271, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.choseinputfile_Button = QtWidgets.QPushButton(self.centralwidget)
        self.choseinputfile_Button.setGeometry(QtCore.QRect(310, 40, 171, 81))
        self.choseinputfile_Button.setObjectName("choseinputfile_Button")
        self.choseoutputfolder_Button = QtWidgets.QPushButton(self.centralwidget)
        self.choseoutputfolder_Button.setGeometry(QtCore.QRect(510, 40, 171, 81))
        self.choseoutputfolder_Button.setObjectName("choseoutputfolder_Button")
        filedecoder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(filedecoder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 22))
        self.menubar.setObjectName("menubar")
        filedecoder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(filedecoder)
        self.statusbar.setObjectName("statusbar")
        filedecoder.setStatusBar(self.statusbar)

        self.retranslateUi(filedecoder)
        QtCore.QMetaObject.connectSlotsByName(filedecoder)

    def retranslateUi(self, filedecoder):
        _translate = QtCore.QCoreApplication.translate
        filedecoder.setWindowTitle(_translate("filedecoder", "文件解码器"))
        self.decode_Button.setText(_translate("filedecoder", "开始解码"))
        self.plainTextEdit.setPlaceholderText(_translate("filedecoder", "请选择需要编码的文件夹"))
        self.choseinputfile_Button.setText(_translate("filedecoder", "选择单个输入文件"))
        self.choseoutputfolder_Button.setText(_translate("filedecoder", "选择输出文件夹"))
