# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encode3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileencoder(object):
    def setupUi(self, fileencoder):
        fileencoder.setObjectName("fileencoder")
        fileencoder.resize(778, 357)
        self.centralwidget = QtWidgets.QWidget(fileencoder)
        self.centralwidget.setObjectName("centralwidget")
        self.encode_Button = QtWidgets.QPushButton(self.centralwidget)
        self.encode_Button.setGeometry(QtCore.QRect(440, 170, 191, 71))
        self.encode_Button.setObjectName("encode_Button")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 271, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.choseinputfile_Button = QtWidgets.QPushButton(self.centralwidget)
        self.choseinputfile_Button.setGeometry(QtCore.QRect(340, 40, 171, 81))
        self.choseinputfile_Button.setObjectName("choseinputfile_Button")
        self.choseoutputfolder_Button = QtWidgets.QPushButton(self.centralwidget)
        self.choseoutputfolder_Button.setGeometry(QtCore.QRect(530, 40, 171, 81))
        self.choseoutputfolder_Button.setObjectName("choseoutputfolder_Button")
        fileencoder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fileencoder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menubar.setObjectName("menubar")
        fileencoder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(fileencoder)
        self.statusbar.setObjectName("statusbar")
        fileencoder.setStatusBar(self.statusbar)

        self.retranslateUi(fileencoder)
        QtCore.QMetaObject.connectSlotsByName(fileencoder)

    def retranslateUi(self, fileencoder):
        _translate = QtCore.QCoreApplication.translate
        fileencoder.setWindowTitle(_translate("fileencoder", "文件编码器"))
        self.encode_Button.setText(_translate("fileencoder", "开始编码"))
        self.plainTextEdit.setPlaceholderText(_translate("fileencoder", "请选择需要编码的文件夹"))
        self.choseinputfile_Button.setText(_translate("fileencoder", "选择单个输入文件"))
        self.choseoutputfolder_Button.setText(_translate("fileencoder", "选择输出文件夹"))
